version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sintrabajo
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "sintrabajo@upeu.pe"
      PGADMIN_DEFAULT_PASSWORD: "sintrabajo"
    ports:
      - "80:80"
    depends_on:
      - postgres
